### ISSUE TITLE
[Compatibility] <Paper/Purpur 1.20.4>

### ISSUE THREAD

**Issue by jan-osicka** [Happy-Hop7/RealisticPlantGrowth#25]
Hello, 
new version 0.9.1 is not compatible with purpur/paper version 1.20.4. Version 0.9.0 works perfectly fine. 

# Steps to Reproduce
1. Install latest build of paper/purpur for 1.20.4
2. Instal latest version of RPG 0.9.1

# Expected Behavior
This version should still support the old versions. 

# Error Logs
`[12:43:20] [Server thread/ERROR]: Error occurred while enabling RealisticPlantGrowth vBETA-0.9.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.PALE_HANGING_MOSS
	at java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at org.bukkit.Material.valueOf(Material.java:124) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at de.nightevolution.realisticplantgrowth.utils.mapper.versions.Version_1_21_4.<init>(Version_1_21_4.java:11) ~[RealisticPlantGrowth-BETA-0.9.1.jar:?]
	at de.nightevolution.realisticplantgrowth.RealisticPlantGrowth.checkServerVersion(RealisticPlantGrowth.java:176) ~[RealisticPlantGrowth-BETA-0.9.1.jar:?]
	at de.nightevolution.realisticplantgrowth.RealisticPlantGrowth.onEnable(RealisticPlantGrowth.java:87) ~[RealisticPlantGrowth-BETA-0.9.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-499]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-499]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-499]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-499]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[paper-1.20.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-499]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:43:20] [Server thread/INFO]: [RealisticPlantGrowth] Disabling RealisticPlantGrowth vBETA-0.9.1`

# Additional Context
Not sure if needs to be fixed, maybe just mention on the main page that this version is not supported. :) 
Sticking with version 0.9.0 which works perfectly.

**Comment by Happy-Hop7** [comment]
Hi @jan-osicka,

Thanks for reporting this issue! 
This is indeed a bug, and I'll work on a fix to ensure compatibility with Paper/Purpur `1.20.4`.

In the meantime, sticking with version `0.9.0` is a good solution.

Thanks again!
